```mermaid
    classDiagram
        class User {
            +int id
            +string email
            +string password_hash
            +datetime created_at
        }
    
        class Session {
            +int id
            +string tmdb_guest_session_id
            +string tmdb_user_session_id
            +datetime created_at
        }
    
        User "1" --> "many" Session : has
```
    
```mermaid
    classDiagram
        class Session {
            +int id
            +string tmdb_guest_session_id
            +string tmdb_user_session_id
            +datetime created_at
        }
```
